### ISSUE TITLE
user icons for mentioned usernames only appear if blog comment is edited

### ISSUE THREAD

**Issue by propertunist** [Elgg/mentions#37]
1. enable the admin option to show images for mentioned users.
2. write a blog comment that includes a mentioned name.
3. save the comment.
   result-> the user icon is not displayed (even when the page is refreshed).

if i edit an existing comment and then save the edit, then the user icon is displayed correctly.

**Comment by hypeJunction** [comment]
This will be fixed when comment object is rendered properly using core listing views. Need to make a PR to core
