### ISSUE TITLE
autocomplete for usernames is broken

### ISSUE THREAD

**Issue by propertunist** [Elgg/mentions#38]
i am not able to get the autocomplete dropdown box to render in any of my sites (1.12.x). if i type a @ symbol followed by some characters i see no dropdown. i have tested with my theme disabled and with/without tinyMCE and the result is the same in all cases.

**Comment by propertunist** [comment]
i have started looking at the code here and found that in autocomplete.js:

a) the timeout of 500ms that is present to delay the check to find out if tinyMCE is instantiated is too short on my machine. if i increase the delay to 1000ms then the tinyMCE code is run, but if i leave it as 500ms then it is not run.

b) when the tinyMCE code is run, the following line generates an error in the console that says that onKeyUp is not defined: 
```
tinymce.editors[i].onKeyUp.add(function (ed, e) {
```

**Comment by propertunist** [comment]
does anyone know if this plugin has been tested with tinyMCE 4+ ?

**Comment by propertunist** [comment]
i have now upgraded mentions in my fork of it to be compatible with tinyMCE 4+ and elgg 2.1.2. the remaining issues are not related to tinyMCE.

**Comment by juho-jaakkola** [comment]
Can you make a PR?

**Comment by propertunist** [comment]
ok, done
