### ISSUE TITLE
Mentions notifications being sent to everyone?

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/mentions#43]
I'm getting notifications from the community about mentions where I'm not the person who was mentioned.

**Comment by juho-jaakkola** [comment]
Furthermore, I haven't even enabled the "Send a notification when someone @mentions you in a post" setting.

**Comment by hypeJunction** [comment]
Odd. Are they your friends?

**Comment by hypeJunction** [comment]
Either way it shouldn't matter, because it uses instant notifications and not subscriptions.
Notifications are enabled by default unless you opt out.
