### ISSUE TITLE
mention in comment should link to comment and not to entity

### ISSUE THREAD

**Issue by jdalsem** [Elgg/mentions#46]

**Comment by hypeJunction** [comment]
I don't see where this is happening. Weird.

**Comment by hypeJunction** [comment]
I suppose the comment URL is the entity URL with `#elgg-comment-` fragment. Does it get stripped perhaps?

**Comment by jdalsem** [comment]
timestamp matches https://elgg.org/discussion/view/2591990/redesigning-wwwelggorg?offset=10#elgg-object-2596644... but you are mentioned and not me... maybe the comment is updated??

**Comment by jdalsem** [comment]
but also:
```
Ismayil Khayredinov mentioned you in a group discussion reply.

To see the full post, click on the link below:
https://elgg.org/discussion/reply/view/2596841/2591990
```

lol... it even says your name... did not notice that

**Comment by jdalsem** [comment]
Ah i know why there is no comment link... it is a group reply :( 

https://elgg.org/discussion/reply/view/2596841/2591990

we should really convert those to full comments ASAP

**Comment by hypeJunction** [comment]
Need to see what notification hooks we have on the community site. Perhaps something is popping up as a results of instant notification hooks matching subscription notification hooks
